# Generated by Django 4.2 on 2023-05-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_rename_name_contact_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name1',
            new_name='name',
        ),
    ]
