# Generated by Django 4.2 on 2023-05-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_rename_name1_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='concern1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email1',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
